name: dai_viet_ki_tran_game
description: Dai Viet Ki Tran match-3 RPG.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.38.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  bloc_effects: ^2.0.1
  flame: 1.35.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  get_it: ^9.2.1
  go_router: ^17.1.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0

dev_dependencies:
  analyzer: ^8.4.1
  bloc_test: ^10.0.0
  build_runner: ^2.12.2
  flame_test: 2.2.2
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.9.5
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/heroes/assassin/
    - assets/images/heroes/guardian/
    - assets/images/heroes/lotus_mage/
    - assets/images/heroes/monk/
    - assets/images/heroes/ranger/
    - assets/images/heroes/spear_guard/
    - assets/images/heroes/strategist/
    - assets/images/heroes/swordsman/
    - assets/images/game/backgrounds/battle/
    - assets/images/game/enemies/bandit/
    - assets/images/game/enemies/goblin_bomber/
    - assets/images/game/enemies/necromancer/
    - assets/images/game/enemies/skeleton_archer/
    - assets/images/game/items/consumables/
    - assets/images/game/items/currency/
    - assets/images/game/items/equipment/
    - assets/images/game/items/materials/
    - assets/images/game/rewards/
    - assets/images/game/tiles/base/
    - assets/images/game/tiles/overlays/
    - assets/images/game/tiles/special/
    - assets/images/game/ui/battle/
    - assets/images/game/vfx/combat/
    - assets/images/game/vfx/elemental/
    - assets/images/game/vfx/projectiles/
    - assets/images/game/vfx/status/
    - assets/game_data/

#  fonts:
#    - family: PlusJakarkaSans
#      fonts:
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraLight.ttf
#          weight: 200
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraBold.ttf
#          weight: 900

flutter_gen:
  output: lib/assets_gen/
  line_length: 1000
  integrations:
    flutter_svg: false
    rive: false
    lottie: false
